# Generated by Django 5.1.2 on 2024-10-16 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_center', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='description',
            field=models.CharField(max_length=250),
        ),
    ]
