# Generated by Django 5.1.2 on 2024-10-16 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_center', '0002_alter_order_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('W', 'รอการยืนยัน'), ('C', 'อยู่ในครัว'), ('AC', 'ทำเสร็จแล้ว'), ('F', 'เสร็จสิ้น'), ('R', 'ยกเลิก')], default='W', max_length=10),
        ),
    ]
